---
abstract: 'selector based streaming template engine'
author:
  - 'Matt S. Trout <mst@shadowcat.co.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Zoom
requires:
  Test::More: 0
  strictures: 0
version: 0.009008_01
